### ISSUE TITLE
PHP warning about _element_validate_integer_positive

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/smart_trim#4]
I'm seeing the following error:

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function _element_validate_integer_positive not found or invalid function name in _form_validate() (line 1482 of /backdrop/core/includes/form.inc).
```

This because the function` _element_validate_integer_positive()` is not needed in backdrop anymore. Instead, change the form element type from `textfield` to `number` and add `#min` and/or `#max` properties.  See https://api.backdropcms.org/node/43955 for more info.

**Comment by jenlampton** [comment]
Here's a patch:
```bash
diff --git a/smart_trim.module b/smart_trim.module
index 8187d992a5..210a96ad04 100644
--- a/smart_trim.module
+++ b/smart_trim.module
@@ -185,11 +185,9 @@ function smart_trim_field_formatter_settings_form($field, $instance, $view_mode,
 
   $element['trim_length'] = array(
     '#title' => t('Trim length'),
-    '#type' => 'textfield',
-    '#size' => 10,
+    '#type' => 'number',
+    '#min' => 0,
     '#default_value' => $settings['trim_length'],
-    // Needs form.inc?
-    '#element_validate' => array('_element_validate_integer_positive'),
     '#required' => TRUE,
   );
 

```

**Comment by jenlampton** [comment]
I've filed a pull request: https://github.com/backdrop-contrib/smart_trim/pull/5

**Comment by opi** [comment]
PR #5 tested and approved.

@fazni, do you mind if I merge the pull request and create a fix release ? Do you still want to be added as module maintainer ? I can take this responsibility

**Comment by fazni** [comment]
@opi ,

Sorry for the delay, if you want we can maintain it together, but tell how can I give you access.

Thanks
Said

**Comment by opi** [comment]
Hi @fazni , thanks for your answer (and the last release). I created a follow-up issue about having me as co-maintainer https://github.com/backdrop-contrib/smart_trim/issues/6
