### ISSUE TITLE
Adding opi as co-maintainer

### ISSUE THREAD

**Issue by opi** [backdrop-contrib/smart_trim#6]
Follow-up https://github.com/backdrop-contrib/smart_trim/issues/4#issuecomment-449726093

- [x] Add @opi as maintainer in README.md: PR https://github.com/backdrop-contrib/smart_trim/pull/7
- [x] Add @opi as admin collaborator in https://github.com/backdrop-contrib/smart_trim/settings/collaboration

**Comment by opi** [comment]
Thanks @fazni  for adding me as co-maintainer

**Comment by fazni** [comment]
Thanks to you @opi .
